### ISSUE TITLE
My Swift 4 port

### ISSUE THREAD

**Issue by apparition47** [dongxinb/DBSphereTagCloud#9]
I ported your great work to [Swift in a detached fork here](https://github.com/apparition47/DBSphereTagCloudSwift). Wasn't sure if you wanted to have a PR or just to keep the Objective-C version for some users. 

Thoughts?

**Comment by dongxinb** [comment]
Thank you for your contribution. I think keeping current version is better, and I will put a link to your repo in the README.

**Comment by apparition47** [comment]
Thanks again!
